name: Release Simple Backup Plugin

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create release artifact
        run: |
          mkdir release
          cp manifest.json main.js styles.css release/

      - name: Zip release folder
        run: zip -r release.zip release

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: obsidian-backup-plugin
          path: release.zip

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "::set-output name=version::$VERSION"

      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: obsidian-backup-plugin

      - name: Unzip release artifact
        run: unzip release.zip

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
